### ISSUE TITLE
The firebase key is being shown to everyone

### ISSUE THREAD

**Issue by Pauisdev** [ConnorMulqueen/spot#4]
Hello, I was searching for something like this and I came across your repository. I wanted to say that in firebase.js your firebase key is there, everyone can see it. You should save it in a different file that you don't commit.

**Comment by ConnorMulqueen** [comment]
Hey,

Thanks for reaching out with the concern. I threw the project up using GitHub Pages to host the static page and currently there's no way to keep API keys private with this kind of hosting. I have the writes/reads limited to the free-tier, so it doesn't bother me.

**Comment by Pauisdev** [comment]
Oh I see, cool then!
